services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: clinic_user
      POSTGRES_PASSWORD: clinic_pass
      POSTGRES_DB: clinic_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: "postgresql+asyncpg://clinic_user:clinic_pass@db:5432/clinic_db"


volumes:
  postgres_data: