"""add unique constraint for active appointment slots

Revision ID: e528e7213efe
Revises: e7649f26f8fb
Create Date: 2026-07-24 16:37:30.769848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e528e7213efe'
down_revision: Union[str, Sequence[str], None] = 'e7649f26f8fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_appointments_active_slot', 'appointments', ['slot_id'], unique=True, postgresql_where=sa.text("status = 'scheduled'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_appointments_active_slot', table_name='appointments', postgresql_where=sa.text("status = 'scheduled'"))
    # ### end Alembic commands ###
